- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "gomgomshrimp/maven-web-app:v0.1-ansible"
      state: started
      ports:
      - "80:8080"

